import { useRef, useState } from "react";
import { post, postForm } from "../../api/client";
import { useApi } from "../../hooks/useApi";

function buildTxtReport(filename, result) {
  const sections = [
    ["SUMMARY", result.summary],
    ["KEY DATA POINTS", result.key_data_points],
    ["ACTION ITEMS", result.action_items],
    ["RED FLAGS", result.red_flags],
  ];
  const lines = [`ANALYSIS REPORT: ${filename}`, "Generated by Workblox — Torres Tech Remote", ""];
  for (const [title, content] of sections) {
    lines.push(title);
    lines.push("-".repeat(title.length));
    if (Array.isArray(content)) {
      content.forEach((item) => lines.push(`  - ${item}`));
    } else {
      lines.push(content);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export default function DocAnalyzer() {
  const [file, setFile] = useState(null);
  const [dragOver, setDragOver] = useState(false);
  const [result, setResult] = useState(null);
  const [filename, setFilename] = useState("");
  const [emailAddr, setEmailAddr] = useState("");
  const [emailSent, setEmailSent] = useState(false);
  const [emailError, setEmailError] = useState(null);
  const [emailSending, setEmailSending] = useState(false);
  const fileRef = useRef();
  const { loading, error, call } = useApi();

  function handleFile(f) {
    if (f) { setFile(f); setResult(null); setEmailSent(false); }
  }

  function onDrop(e) {
    e.preventDefault();
    setDragOver(false);
    handleFile(e.dataTransfer.files[0]);
  }

  async function handleSubmit(e) {
    e.preventDefault();
    if (!file) return;
    const fd = new FormData();
    fd.append("file", file);
    const data = await call(() => postForm("/api/doc", fd));
    if (data) { setResult(data); setFilename(file.name); }
  }

  function downloadTxt() {
    const txt = buildTxtReport(filename, result);
    const blob = new Blob([txt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename.replace(/\.[^.]+$/, "") + "_report.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  async function sendEmail(e) {
    e.preventDefault();
    setEmailError(null);
    setEmailSending(true);
    try {
      await post("/api/doc/email", { email: emailAddr, filename, result });
      setEmailSent(true);
    } catch (err) {
      setEmailError(err.message);
    } finally {
      setEmailSending(false);
    }
  }

  return (
    <>
      <h1 className="page-title">Doc <span>Analyzer</span></h1>
      <p className="page-subtitle">Upload a PDF, TXT, or MD file — get a structured AI summary.</p>

      <form onSubmit={handleSubmit}>
        <div
          className={`drop-zone${dragOver ? " active" : ""}`}
          onClick={() => fileRef.current.click()}
          onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={onDrop}
        >
          <input
            ref={fileRef}
            type="file"
            accept=".pdf,.txt,.md"
            onChange={(e) => handleFile(e.target.files[0])}
          />
          {file ? (
            <p className="drop-label" style={{ color: "#111" }}>{file.name}</p>
          ) : (
            <>
              <p className="drop-label">Drop a file here or click to browse</p>
              <p className="drop-hint">PDF, TXT, or MD — max 10 MB</p>
            </>
          )}
        </div>

        <button type="submit" className="submit-btn" disabled={loading || !file}>
          {loading ? "Analyzing..." : "Analyze"}
        </button>
      </form>

      {error && <div className="error-banner" style={{ marginTop: 16 }}>{error}</div>}

      {result && !loading && (
        <>
          <div style={{ marginTop: 24 }}>
            <DocSection title="Summary" content={result.summary} />
            <DocSection title="Key Data Points" content={result.key_data_points} />
            <DocSection title="Action Items" content={result.action_items} />
            <DocSection title="Red Flags" content={result.red_flags} />
          </div>

          <div style={{ display: "flex", gap: 10, marginTop: 8, flexWrap: "wrap" }}>
            <button className="copy-btn" style={{ padding: "8px 18px", fontSize: "0.88rem" }} onClick={downloadTxt}>
              Download TXT
            </button>
          </div>

          <div style={{ marginTop: 20 }}>
            <form onSubmit={sendEmail} style={{ display: "flex", gap: "0.6rem" }}>
              <input
                type="email"
                className="search-box"
                style={{
                  flex: 1, padding: "0.7rem 1rem", background: "#fff",
                  border: "1.5px solid #ddd", borderRadius: 8,
                  fontFamily: "inherit", fontSize: "0.95rem", outline: "none",
                }}
                placeholder="Email the report to..."
                value={emailAddr}
                onChange={(e) => setEmailAddr(e.target.value)}
              />
              <button
                type="submit"
                className="submit-btn"
                style={{ padding: "0.7rem 1.4rem", fontSize: "0.95rem" }}
                disabled={emailSending || !emailAddr.trim()}
              >
                {emailSending ? "Sending..." : "Send"}
              </button>
            </form>
            {emailSent && <p style={{ color: "#16a34a", fontSize: "0.88rem", marginTop: 8 }}>Report sent to {emailAddr}</p>}
            {emailError && <div className="error-banner" style={{ marginTop: 8 }}>{emailError}</div>}
          </div>
        </>
      )}
    </>
  );
}

function DocSection({ title, content }) {
  return (
    <div className="result-card">
      <div className="result-label">{title}</div>
      {Array.isArray(content) ? (
        <ul className="section-list">
          {content.map((item, i) => <li key={i}>{item}</li>)}
        </ul>
      ) : (
        <p className="explanation-text">{content}</p>
      )}
    </div>
  );
}
