import { useRef, useState } from "react";
import { Trans, useTranslation } from "react-i18next";
import { BASE_URL, post, postForm } from "../../api/client";
import { useApi } from "../../hooks/useApi";
import { compressImage } from "../../utils/imageCapture";

const MAX_PHOTOS = 6;
const IMAGE_EXTENSIONS = /\.(jpe?g|png|heic|heif|webp|gif|bmp|tiff?)$/i;

function isImageFile(f) {
  // Some browsers (drag-and-drop especially) report HEIC files with no
  // useful MIME type, so fall back to checking the extension too.
  return f.type.startsWith("image/") || IMAGE_EXTENSIONS.test(f.name);
}

function buildTxtReport(filename, result) {
  const sections = [
    ["SUMMARY", result.summary],
    ["KEY DATA POINTS", result.key_data_points],
    ["ACTION ITEMS", result.action_items],
    ["RED FLAGS", result.red_flags],
  ];
  const lines = [`ANALYSIS REPORT: ${filename}`, "Generated by Workblox — Torres Tech Remote", ""];
  for (const [title, content] of sections) {
    lines.push(title);
    lines.push("-".repeat(title.length));
    if (Array.isArray(content)) {
      content.forEach((item) => lines.push(`  - ${item}`));
    } else {
      lines.push(content);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export default function DocAnalyzer() {
  const { t, i18n } = useTranslation("docAnalyzer");
  const [file, setFile] = useState(null);
  const [dragOver, setDragOver] = useState(false);
  const [photos, setPhotos] = useState([]); // [{ id, blob, previewUrl }]
  const [photoError, setPhotoError] = useState(null);
  const [result, setResult] = useState(null);
  const [filename, setFilename] = useState("");
  const [emailAddr, setEmailAddr] = useState("");
  const [emailSent, setEmailSent] = useState(false);
  const [emailError, setEmailError] = useState(null);
  const [emailSending, setEmailSending] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);
  const fileRef = useRef();
  const { loading, error, call } = useApi();

  function clearPhotos() {
    photos.forEach((p) => URL.revokeObjectURL(p.previewUrl));
    setPhotos([]);
  }

  function handleFile(f) {
    if (f) { clearPhotos(); setFile(f); setResult(null); setEmailSent(false); }
  }

  async function addPhotoFiles(rawFiles) {
    const files = Array.from(rawFiles || []).filter(Boolean);
    if (files.length === 0) return;
    if (photos.length + files.length > MAX_PHOTOS) {
      setPhotoError(t("photo.limit", { max: MAX_PHOTOS }));
      return;
    }
    setPhotoError(null);
    setFile(null);
    setResult(null);
    setEmailSent(false);
    const added = [];
    for (const rawFile of files) {
      let blob;
      try {
        blob = await compressImage(rawFile);
      } catch {
        // Couldn't decode client-side (e.g. HEIC on a browser with no HEIC
        // decoder) — upload the original file and let the backend normalize it.
        blob = rawFile;
      }
      added.push({ id: `${Date.now()}-${photos.length + added.length}`, blob, previewUrl: URL.createObjectURL(rawFile) });
    }
    setPhotos((prev) => [...prev, ...added]);
  }

  // The drop-zone now accepts either a document or one/more photos — route
  // dropped/selected files to whichever pipeline fits instead of always
  // treating them as a single document.
  function handleDroppedOrSelected(fileList) {
    const files = Array.from(fileList || []).filter(Boolean);
    if (files.length === 0) return;
    const images = files.filter(isImageFile);
    if (images.length > 0) {
      addPhotoFiles(images);
      return;
    }
    handleFile(files[0]);
  }

  function onDrop(e) {
    e.preventDefault();
    setDragOver(false);
    handleDroppedOrSelected(e.dataTransfer.files);
  }

  async function handlePhotoInput(e) {
    const files = e.target.files;
    e.target.value = "";
    await addPhotoFiles(files);
  }

  function removePhoto(id) {
    setPhotos((prev) => {
      const target = prev.find((p) => p.id === id);
      if (target) URL.revokeObjectURL(target.previewUrl);
      return prev.filter((p) => p.id !== id);
    });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    if (!file && photos.length === 0) return;
    const fd = new FormData();
    if (photos.length > 0) {
      photos.forEach((p, i) => fd.append("images", p.blob, `photo-${i + 1}.jpg`));
    } else {
      fd.append("file", file);
    }
    fd.append("language", i18n.language);
    const data = await call(() => postForm("/api/doc", fd));
    if (data) { setResult(data); setFilename(photos.length > 0 ? t("photo.filenameFallback") : file.name); }
  }

  function downloadTxt() {
    const txt = buildTxtReport(filename, result);
    const blob = new Blob([txt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename.replace(/\.[^.]+$/, "") + "_report.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  async function downloadPdf() {
    setPdfLoading(true);
    try {
      const res = await fetch(`${BASE_URL}/api/doc/download/pdf`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": `Bearer ${localStorage.getItem("wb_token")}` },
        body: JSON.stringify({ filename, result }),
      });
      if (!res.ok) throw new Error("PDF generation failed");
      const blob = await res.blob();
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement("a");
      a.href     = url;
      a.download = filename.replace(/\.[^.]+$/, "") + "_report.pdf";
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      alert(err.message);
    } finally {
      setPdfLoading(false);
    }
  }

  async function sendEmail(e) {
    e.preventDefault();
    setEmailError(null);
    setEmailSending(true);
    try {
      await post("/api/doc/email", { email: emailAddr, filename, result });
      setEmailSent(true);
    } catch (err) {
      setEmailError(err.message);
    } finally {
      setEmailSending(false);
    }
  }

  return (
    <>
      <h1 className="page-title"><Trans t={t} i18nKey="title"><span /></Trans></h1>
      <p className="page-subtitle">{t("subtitle")}</p>

      <form onSubmit={handleSubmit}>
        <div
          className={`drop-zone${dragOver ? " active" : ""}`}
          onClick={() => fileRef.current.click()}
          onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={onDrop}
        >
          <input
            ref={fileRef}
            type="file"
            accept=".pdf,.txt,.md"
            onChange={(e) => handleDroppedOrSelected(e.target.files)}
          />
          {file ? (
            <p className="drop-label" style={{ color: "#111" }}>{file.name}</p>
          ) : (
            <>
              <p className="drop-label">{t("dropLabel")}</p>
              <p className="drop-hint">{t("dropHint")}</p>
            </>
          )}
        </div>

        <div className="photo-capture">
          <div className="photo-capture-divider">{t("photo.or")}</div>
          <div className="photo-capture-buttons">
            <label className="photo-capture-btn">
              {t("photo.take")}
              <input type="file" accept="image/*" capture="environment" onChange={handlePhotoInput} />
            </label>
            <label className="photo-capture-btn">
              {t("photo.choose")}
              <input type="file" accept="image/*" multiple onChange={handlePhotoInput} />
            </label>
          </div>
          <p className="photo-capture-hint">{t("photo.hint")}</p>
          {photoError && <div className="error-banner" style={{ marginTop: 8 }}>{photoError}</div>}
          {photos.length > 0 && (
            <div className="photo-thumbs">
              {photos.map((p, i) => (
                <PhotoThumb
                  key={p.id}
                  photo={p}
                  label={t("photo.pageLabel", { n: i + 1 })}
                  removeLabel={t("photo.removeLabel", { n: i + 1 })}
                  onRemove={() => removePhoto(p.id)}
                />
              ))}
            </div>
          )}
        </div>

        <button type="submit" className="submit-btn" disabled={loading || (!file && photos.length === 0)}>
          {loading ? t("analyzing") : t("analyze")}
        </button>
      </form>

      {error && <div className="error-banner" style={{ marginTop: 16 }}>{error}</div>}

      {result && !loading && (
        <>
          <div style={{ marginTop: 24 }}>
            <DocSection title={t("sections.summary")} content={result.summary} />
            <DocSection title={t("sections.keyDataPoints")} content={result.key_data_points} />
            <DocSection title={t("sections.actionItems")} content={result.action_items} />
            <DocSection title={t("sections.redFlags")} content={result.red_flags} />
          </div>

          <div style={{ marginTop: 8, display: "flex", gap: "0.6rem", flexWrap: "wrap" }}>
            <button className="copy-btn" style={{ padding: "8px 18px", fontSize: "0.88rem" }} onClick={downloadTxt}>
              {t("download.txt")}
            </button>
            <button className="copy-btn" style={{ padding: "8px 18px", fontSize: "0.88rem" }}
              onClick={downloadPdf} disabled={pdfLoading}>
              {pdfLoading ? t("download.generating") : t("download.pdf")}
            </button>
          </div>

          <div style={{ marginTop: 20 }}>
            <form onSubmit={sendEmail} style={{ display: "flex", gap: "0.6rem" }}>
              <input
                type="email"
                style={{
                  flex: 1, padding: "0.7rem 1rem", background: "#fff",
                  border: "1.5px solid #ddd", borderRadius: 8,
                  fontFamily: "inherit", fontSize: "0.95rem", outline: "none",
                }}
                placeholder={t("email.placeholder")}
                value={emailAddr}
                onChange={(e) => setEmailAddr(e.target.value)}
              />
              <button
                type="submit"
                className="submit-btn"
                style={{ padding: "0.7rem 1.4rem", fontSize: "0.95rem" }}
                disabled={emailSending || !emailAddr.trim()}
              >
                {emailSending ? t("email.sending") : t("email.send")}
              </button>
            </form>
            {emailSent && <p style={{ color: "#16a34a", fontSize: "0.88rem", marginTop: 8 }}>{t("email.sent", { email: emailAddr })}</p>}
            {emailError && <div className="error-banner" style={{ marginTop: 8 }}>{emailError}</div>}
          </div>
        </>
      )}
    </>
  );
}

function DocSection({ title, content }) {
  return (
    <div className="result-card">
      <div className="result-label">{title}</div>
      {Array.isArray(content) ? (
        <ul className="section-list">
          {content.map((item, i) => <li key={i}>{item}</li>)}
        </ul>
      ) : (
        <p className="explanation-text">{content}</p>
      )}
    </div>
  );
}

function PhotoThumb({ photo, label, removeLabel, onRemove }) {
  const [broken, setBroken] = useState(false);
  return (
    <div className="photo-thumb">
      {!broken ? (
        <img src={photo.previewUrl} alt={label} onError={() => setBroken(true)} />
      ) : (
        <div className="photo-thumb-fallback">{label}</div>
      )}
      <button type="button" onClick={onRemove} aria-label={removeLabel}>&times;</button>
    </div>
  );
}
