"""
Printed report details that clients see: timestamps in the user's own time
zone (the server clock is UTC), section headings never stranded alone at the
bottom of a page, and the Contract Analyzer's risk level drawn as a badge.
"""
import io
import re
from datetime import datetime
from zoneinfo import ZoneInfo

import pdfplumber
import pytest

from app import create_app, db
from app.models import User
from app.services.auth import create_token
from app.services.email import _generate_pdf
from app.services.entitlements import set_entitlements
from app.services.localtime import local_now

HEADINGS = {"Document Overview", "Key Obligations", "Red Flags",
            "Missing Standard Clauses", "Recommendation"}


def _pages(pdf_bytes):
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        return [page.extract_text() or "" for page in pdf.pages]


def _last_body_line(page_text):
    lines = [l.strip() for l in page_text.splitlines()
             if l.strip() and not l.strip().startswith("Generated by")]
    return lines[-1] if lines else ""


def _contract_txt(n_obligations):
    lines = ["Contract Analyzer — NDA", "=" * 60, "High risk", "",
             "Document Overview", "-" * 40, "Overview text. " * 20, "",
             "Key Obligations", "-" * 40]
    lines += [f"{i}. Obligation {i}" for i in range(1, n_obligations + 1)]
    for heading in ("Red Flags", "Missing Standard Clauses"):
        lines += ["", heading, "-" * 40] + [f"{i}. item {i}" for i in range(1, 6)]
    lines += ["", "Recommendation", "-" * 40, "Text. " * 40]
    return "\n".join(lines)


# ── Time zone ────────────────────────────────────────────────────────────────

def test_local_now_uses_the_callers_time_zone():
    app = create_app()
    with app.test_request_context(headers={"X-Timezone": "America/New_York"}):
        assert local_now().tzinfo == ZoneInfo("America/New_York")


@pytest.mark.parametrize("header", [None, "", "Not/AZone", "../../etc/passwd"])
def test_local_now_falls_back_to_utc(header):
    app = create_app()
    headers = {"X-Timezone": header} if header is not None else {}
    with app.test_request_context(headers=headers):
        assert local_now().utcoffset().total_seconds() == 0


def test_x_timezone_is_an_allowed_cors_header():
    # The apps send X-Timezone on every request; if the server stopped
    # allowing it, browsers would block every call, not just reports.
    from app.config import Config
    app = create_app()
    with app.test_client() as c:
        rv = c.options("/api/auth/login", headers={
            "Origin": list(Config.ALLOWED_ORIGINS)[0],
            "Access-Control-Request-Method": "POST",
            "Access-Control-Request-Headers": "authorization, content-type, x-timezone",
        })
    assert "X-Timezone" in rv.headers.get("Access-Control-Allow-Headers", "")


# ── Business report PDF ──────────────────────────────────────────────────────

def test_business_pdf_never_ends_a_page_on_a_heading():
    # Sweep the content length so every heading lands at every height on the
    # page at some point, including the last few millimetres.
    for n in range(1, 45):
        for page in _pages(_generate_pdf("Contract Analyzer — NDA", _contract_txt(n), "en")):
            assert _last_body_line(page) not in HEADINGS, f"stranded heading at n={n}"


def test_business_pdf_risk_badge_replaces_the_plain_risk_line():
    pdf = _generate_pdf("Contract Analyzer — NDA", _contract_txt(3), "en",
                        badge={"label": "High risk", "level": "high"})
    assert _pages(pdf)[0].count("High risk") == 1


def test_business_pdf_ignores_an_unknown_badge_level():
    pdf = _generate_pdf("Contract Analyzer — NDA", _contract_txt(3), "en",
                        badge={"label": "High risk", "level": "purple"})
    # No badge drawn, so the risk line stays in the body as before.
    assert _pages(pdf)[0].count("High risk") == 1


# ── Doc Analyzer PDF (real route, real auth) ─────────────────────────────────

@pytest.fixture
def doc_client(tmp_path, monkeypatch):
    from app.config import Config
    monkeypatch.setattr(Config, "SQLALCHEMY_DATABASE_URI", f"sqlite:///{tmp_path}/layout_test.db")
    app = create_app()
    # The PDF route allows 10 downloads an hour; the page-break sweep needs more.
    from app import limiter
    monkeypatch.setattr(limiter, "enabled", False)
    email = "layout-test@example.com"
    with app.app_context():
        user = User(email=email, name="Layout Test", is_active=True, email_verified=True,
                    has_personal=True, has_business=False)
        db.session.add(user)
        db.session.commit()
        set_entitlements(user.id, {"doc"}, source="self_service", app="personal")
        token = create_token(sub=email, name="Layout Test", has_personal=True, has_business=False)
    with app.test_client() as c:
        yield c, token


def _doc_pdf(client, token, n_points, tz="America/New_York"):
    result = {
        "summary": "Summary text. " * 15,
        "key_data_points": [f"Data point {i} with some detail" for i in range(1, n_points + 1)],
        "action_items": [f"Action {i}" for i in range(1, 5)],
        "red_flags": [f"Flag {i}" for i in range(1, 5)],
    }
    rv = client.post("/api/doc/download/pdf",
                     json={"filename": "notice.pdf", "result": result, "language": "en"},
                     headers={"Authorization": f"Bearer {token}", "X-Timezone": tz})
    assert rv.status_code == 200
    return rv.data


def test_doc_pdf_prints_the_users_local_time(doc_client):
    client, token = doc_client
    text = _pages(_doc_pdf(client, token, 3, tz="Asia/Tokyo"))[0]
    stamp = re.search(r"(\w+ \d{2}, \d{4})\s+(\d{2}:\d{2})", text)
    printed = datetime.strptime(f"{stamp.group(1)} {stamp.group(2)}", "%B %d, %Y %H:%M")
    tokyo_now = datetime.now(ZoneInfo("Asia/Tokyo")).replace(tzinfo=None, second=0, microsecond=0)
    assert abs((printed - tokyo_now).total_seconds()) <= 120


def test_doc_pdf_never_ends_a_page_on_a_heading(doc_client):
    client, token = doc_client
    doc_headings = {"Summary", "Key Data Points", "Action Items", "Red Flags"}
    for n in range(1, 50, 2):
        for page in _pages(_doc_pdf(client, token, n)):
            assert _last_body_line(page) not in doc_headings, f"stranded heading at n={n}"
