import base64
import json
import re
import urllib.request

from flask import current_app

from .auth import create_verification_token


def _generate_pdf(subject, txt_content):
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    W = pdf.epw  # 170mm effective width

    def safe(text):
        text = (text
            .replace("—", " - ").replace("–", " - ")
            .replace("‘", "'").replace("’", "'")
            .replace("“", '"').replace("”", '"')
            .replace("•", "-").replace(" ", " "))
        return text.encode("latin-1", errors="replace").decode("latin-1")

    def cell_ln(h, text, font_size=9, bold=False, color=(31, 41, 55)):
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B" if bold else "", font_size)
        pdf.set_text_color(*color)
        pdf.multi_cell(W, h, safe(text))
        pdf.set_x(pdf.l_margin)

    # Dark header bar
    pdf.set_fill_color(30, 41, 59)
    pdf.rect(0, 0, 210, 32, "F")
    pdf.set_text_color(148, 163, 184)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_xy(20, 8)
    pdf.cell(W, 5, "TORRES TECH REMOTE  |  WORKBLOX BUSINESS")
    pdf.set_xy(20, 16)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(W, 8, safe(subject[:90]))
    pdf.set_xy(20, 40)

    lines = txt_content.split("\n")
    i = 0
    first = True

    while i < len(lines):
        line = lines[i]
        next_line = lines[i + 1] if i + 1 < len(lines) else ""
        is_sep = bool(re.match(r"^[=\-]{8,}$", line.strip()))
        next_is_sep = bool(re.match(r"^[=\-]{8,}$", next_line.strip()))

        if is_sep:
            i += 1
            continue

        if next_is_sep and line.strip():
            if first:
                first = False
                i += 2
                continue
            pdf.ln(5)
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(37, 99, 235)
            pdf.cell(W, 7, safe(line.strip()))
            pdf.ln(7)
            pdf.set_x(pdf.l_margin)
            pdf.set_draw_color(229, 231, 235)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(3)
            pdf.set_x(pdf.l_margin)
            i += 2
            continue

        if not line.strip():
            pdf.ln(2)
            pdf.set_x(pdf.l_margin)
            i += 1
            continue

        if re.match(r"^\d+\.\s", line):
            cell_ln(5.5, line, font_size=9)
            i += 1
            continue

        cell_ln(6, line.strip(), font_size=10)
        i += 1

    # Footer — disable auto page break so set_y near bottom doesn't trigger new page
    pdf.set_auto_page_break(False)
    pdf.set_y(pdf.h - 15)
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(W, 5, "Generated by Workblox Business  |  Torres Tech Remote", align="C")

    return bytes(pdf.output())


def send_pdf_email(to_email, subject, txt_content, filename="report"):
    api_key = current_app.config.get("SENDGRID_API_KEY", "")
    mail_from = current_app.config.get("MAIL_FROM", "")
    if not api_key or not mail_from:
        return False
    pdf_bytes = _generate_pdf(subject, txt_content)
    pdf_b64 = base64.b64encode(pdf_bytes).decode()
    return _sendgrid_post({
        "personalizations": [{"to": [{"email": to_email}]}],
        "from": {"email": mail_from, "name": "Workblox Business"},
        "subject": subject,
        "content": [{"type": "text/plain", "value": f"Please find your {subject} report attached."}],
        "attachments": [{
            "content": pdf_b64,
            "filename": f"{filename}.pdf",
            "type": "application/pdf",
            "disposition": "attachment",
        }],
    }, api_key)


def _sendgrid_post(payload_dict, api_key):
    payload = json.dumps(payload_dict).encode()
    req = urllib.request.Request(
        "https://api.sendgrid.com/v3/mail/send",
        data=payload,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as res:
            return res.status == 202
    except Exception:
        return False


def send_report_email(to_email, subject, txt_body, html_body):
    api_key = current_app.config.get("SENDGRID_API_KEY", "")
    mail_from = current_app.config.get("MAIL_FROM", "")
    if not api_key or not mail_from:
        return False
    return _sendgrid_post({
        "personalizations": [{"to": [{"email": to_email}]}],
        "from": {"email": mail_from, "name": "Workblox Business"},
        "subject": subject,
        "content": [
            {"type": "text/plain", "value": txt_body},
            {"type": "text/html", "value": html_body},
        ],
    }, api_key)


def send_verification_email(email, name):
    api_key = current_app.config.get("SENDGRID_API_KEY", "")
    mail_from = current_app.config.get("MAIL_FROM", "")
    if not api_key or not mail_from:
        return False

    token = create_verification_token(email)
    app_url = current_app.config.get("APP_URL", "http://localhost:5000")
    verify_url = f"{app_url}/api/auth/verify/{token}"

    payload = json.dumps({
        "personalizations": [{"to": [{"email": email, "name": name}]}],
        "from": {"email": mail_from, "name": "Workblox"},
        "subject": "Verify your Workblox email",
        "content": [
            {
                "type": "text/plain",
                "value": (
                    f"Hi {name},\n\n"
                    f"Verify your Workblox email:\n{verify_url}\n\n"
                    "This link expires in 24 hours."
                ),
            },
            {
                "type": "text/html",
                "value": f"""<!DOCTYPE html>
<html>
<body style="font-family:Inter,system-ui,sans-serif;max-width:480px;margin:40px auto;padding:0 24px;color:#111">
  <p style="font-size:1rem;font-weight:800">Torres<span style="color:#FF6B00">Tech</span> Remote &mdash; Workblox</p>
  <h2 style="margin-top:0">Verify your email</h2>
  <p>Hi {name},</p>
  <p>Click the button below to verify your email address and complete your Workblox signup.</p>
  <a href="{verify_url}"
     style="display:inline-block;background:#FF6B00;color:#fff;padding:12px 28px;
            text-decoration:none;border-radius:8px;font-weight:700;margin:16px 0">
    Verify Email
  </a>
  <p style="color:#666;font-size:0.85rem">
    Link expires in 24 hours. If you didn't sign up for Workblox, ignore this email.
  </p>
</body>
</html>""",
            },
        ],
    }).encode()

    req = urllib.request.Request(
        "https://api.sendgrid.com/v3/mail/send",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req) as res:
            return res.status == 202
    except Exception:
        return False


def send_admin_notification(new_user_email, new_user_name):
    api_key = current_app.config.get("SENDGRID_API_KEY", "")
    mail_from = current_app.config.get("MAIL_FROM", "")
    if not api_key or not mail_from:
        return False

    admin_email = "pedro_torres@torrestechremote.com"
    payload = json.dumps({
        "personalizations": [{"to": [{"email": admin_email}]}],
        "from": {"email": mail_from, "name": "Workblox"},
        "subject": f"New signup: {new_user_name}",
        "content": [
            {
                "type": "text/html",
                "value": f"""<!DOCTYPE html>
<html>
<body style="font-family:Inter,system-ui,sans-serif;max-width:480px;margin:40px auto;padding:0 24px;color:#111">
  <p style="font-size:1rem;font-weight:800">Torres<span style="color:#FF6B00">Tech</span> Remote &mdash; Workblox</p>
  <h2 style="margin-top:0">New client signup</h2>
  <p><strong>{new_user_name}</strong> just signed up and is pending activation.</p>
  <table style="margin:16px 0;border-collapse:collapse">
    <tr><td style="color:#666;padding-right:16px">Name</td><td><strong>{new_user_name}</strong></td></tr>
    <tr><td style="color:#666;padding-right:16px">Email</td><td><strong>{new_user_email}</strong></td></tr>
  </table>
  <p>Log in to the admin panel to activate their account.</p>
</body>
</html>""",
            }
        ],
    }).encode()

    req = urllib.request.Request(
        "https://api.sendgrid.com/v3/mail/send",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req) as res:
            return res.status == 202
    except Exception:
        return False
