import { useState } from "react";
import { useApi } from "../../hooks/useApi";
import { post } from "../../api/client";

function slug(text) {
  return text.toLowerCase().replace(/\s+/g, "_").replace(/[^a-z0-9_]/g, "") || "hiring_package";
}

function buildTxt(data, jobTitle, department) {
  const title = department ? `${jobTitle} — ${department}` : jobTitle;
  const lines = [`HIRING PACKAGE — ${title.toUpperCase()}`, "=".repeat(60), ""];
  lines.push("POSITION SUMMARY", "-".repeat(40), data.position_summary || "", "");
  lines.push("INTERVIEW QUESTIONS", "-".repeat(40));
  (data.interview_questions || []).forEach((q, i) => lines.push(`${i + 1}. ${q}`));
  lines.push("", "EVALUATION CRITERIA", "-".repeat(40));
  (data.evaluation_criteria || []).forEach((c, i) => lines.push(`${i + 1}. ${c}`));
  if (data.red_flags?.length) {
    lines.push("", "RED FLAGS TO WATCH", "-".repeat(40));
    data.red_flags.forEach((f, i) => lines.push(`${i + 1}. ${f}`));
  }
  if (data.onboarding_tips?.length) {
    lines.push("", "ONBOARDING TIPS", "-".repeat(40));
    data.onboarding_tips.forEach((t, i) => lines.push(`${i + 1}. ${t}`));
  }
  return lines.join("\n");
}

function buildMd(data, jobTitle, department) {
  const title = department ? `${jobTitle} — ${department}` : jobTitle;
  const lines = [`# Hiring Package — ${title}`, "", "## Position Summary", data.position_summary || "", ""];
  lines.push("## Interview Questions");
  (data.interview_questions || []).forEach((q) => lines.push(`- ${q}`));
  lines.push("", "## Evaluation Criteria");
  (data.evaluation_criteria || []).forEach((c) => lines.push(`- ${c}`));
  if (data.red_flags?.length) {
    lines.push("", "## Red Flags to Watch");
    data.red_flags.forEach((f) => lines.push(`- ${f}`));
  }
  if (data.onboarding_tips?.length) {
    lines.push("", "## Onboarding Tips");
    data.onboarding_tips.forEach((t) => lines.push(`- ${t}`));
  }
  return lines.join("\n");
}

function buildHtmlEmail(data, jobTitle, department) {
  const title = department ? `${jobTitle} — ${department}` : jobTitle;
  const li = (items) => (items || []).map((x) => `<li style="margin-bottom:6px">${x}</li>`).join("");
  return `<!DOCTYPE html>
<html>
<body style="font-family:Inter,system-ui,sans-serif;max-width:600px;margin:40px auto;padding:0 24px;color:#111">
  <p style="font-size:1rem;font-weight:800">Torres<span style="color:#2563eb">Tech</span> Remote &mdash; Workblox Business</p>
  <h2 style="margin-top:0">Hiring Package — ${title}</h2>
  <h3 style="color:#2563eb;margin-bottom:4px">Position Summary</h3>
  <p style="line-height:1.65">${data.position_summary || ""}</p>
  <h3 style="color:#2563eb;margin-bottom:4px">Interview Questions</h3>
  <ol style="padding-left:1.2rem">${li(data.interview_questions)}</ol>
  <h3 style="color:#2563eb;margin-bottom:4px">Evaluation Criteria</h3>
  <ol style="padding-left:1.2rem">${li(data.evaluation_criteria)}</ol>
  ${data.red_flags?.length ? `<h3 style="color:#b45309;margin-bottom:4px">Red Flags to Watch</h3><ul style="padding-left:1.2rem">${li(data.red_flags)}</ul>` : ""}
  ${data.onboarding_tips?.length ? `<h3 style="color:#2563eb;margin-bottom:4px">Onboarding Tips</h3><ul style="padding-left:1.2rem">${li(data.onboarding_tips)}</ul>` : ""}
  <p style="color:#888;font-size:0.82rem;margin-top:24px">Generated by Workblox Business &mdash; Torres Tech Remote</p>
</body>
</html>`;
}

function triggerDownload(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function HiringManager() {
  const { loading, error, call } = useApi();
  const [jobTitle, setJobTitle] = useState("");
  const [department, setDepartment] = useState("");
  const [requirements, setRequirements] = useState("");
  const [data, setData] = useState(null);
  const [emailTo, setEmailTo] = useState(localStorage.getItem("wbb_email") || "");
  const [emailSent, setEmailSent] = useState(false);
  const [emailLoading, setEmailLoading] = useState(false);
  const [emailError, setEmailError] = useState(null);

  async function handleSubmit(e) {
    e.preventDefault();
    setData(null);
    setEmailSent(false);
    setEmailError(null);
    const result = await call(() => post("/api/biz/hiring-manager", {
      job_title: jobTitle,
      department,
      requirements,
    }));
    if (result) setData(result);
  }

  function copyText(text) {
    navigator.clipboard.writeText(Array.isArray(text) ? text.join("\n") : text);
  }

  function handleDownload(format) {
    const base = slug(jobTitle);
    if (format === "txt") triggerDownload(buildTxt(data, jobTitle, department), `${base}.txt`, "text/plain");
    else if (format === "md") triggerDownload(buildMd(data, jobTitle, department), `${base}.md`, "text/markdown");
    else if (format === "pdf") window.print();
  }

  async function handleEmail(e) {
    e.preventDefault();
    setEmailLoading(true);
    setEmailError(null);
    setEmailSent(false);
    try {
      await post("/api/biz/send-report", {
        email: emailTo,
        subject: `Hiring Package — ${jobTitle}${department ? ` (${department})` : ""}`,
        content_txt: buildTxt(data, jobTitle, department),
        content_html: buildHtmlEmail(data, jobTitle, department),
      });
      setEmailSent(true);
    } catch (err) {
      setEmailError(err.message);
    } finally {
      setEmailLoading(false);
    }
  }

  return (
    <div>
      <h1 className="page-title">Hiring <span>Manager</span></h1>
      <p className="page-subtitle">Generate interview questions, evaluation criteria, and a hiring package for any role.</p>

      <form onSubmit={handleSubmit} className="no-print" style={{ display: "flex", flexDirection: "column", gap: "0.75rem", marginBottom: "1.5rem" }}>
        <input
          type="text"
          placeholder="Job title (e.g. Senior Software Engineer)"
          value={jobTitle}
          onChange={(e) => setJobTitle(e.target.value)}
          required
          disabled={loading}
          style={{ padding: "0.75rem 0.9rem", border: "1.5px solid var(--border)", borderRadius: "var(--radius)", fontFamily: "inherit", fontSize: "0.92rem", outline: "none" }}
        />
        <input
          type="text"
          placeholder="Department (e.g. Engineering)"
          value={department}
          onChange={(e) => setDepartment(e.target.value)}
          disabled={loading}
          style={{ padding: "0.75rem 0.9rem", border: "1.5px solid var(--border)", borderRadius: "var(--radius)", fontFamily: "inherit", fontSize: "0.92rem", outline: "none" }}
        />
        <textarea
          placeholder="Key requirements and responsibilities..."
          value={requirements}
          onChange={(e) => setRequirements(e.target.value)}
          rows={4}
          disabled={loading}
          style={{ padding: "0.75rem 0.9rem", border: "1.5px solid var(--border)", borderRadius: "var(--radius)", fontFamily: "inherit", fontSize: "0.92rem", outline: "none", resize: "vertical" }}
        />
        <button type="submit" className="submit-btn" disabled={loading}>
          {loading ? "Generating…" : "Generate Hiring Package"}
        </button>
      </form>

      {error && <div className="error-banner no-print">{error}</div>}

      {data && (
        <>
          <div className="print-header" style={{ display: "none" }}>
            <strong>Hiring Package — {jobTitle}{department ? ` (${department})` : ""}</strong>
          </div>

          <div className="result-card">
            <div className="result-header">
              <p className="result-label">Position Summary</p>
            </div>
            <p style={{ fontSize: "0.95rem", lineHeight: 1.65 }}>{data.position_summary}</p>
          </div>

          <div className="result-card">
            <div className="result-header">
              <p className="result-label">Interview Questions</p>
              <button className="copy-btn no-print" onClick={() => copyText(data.interview_questions)}>Copy</button>
            </div>
            <ul className="section-list">
              {(data.interview_questions || []).map((q, i) => <li key={i}>{q}</li>)}
            </ul>
          </div>

          <div className="result-card">
            <div className="result-header">
              <p className="result-label">Evaluation Criteria</p>
              <button className="copy-btn no-print" onClick={() => copyText(data.evaluation_criteria)}>Copy</button>
            </div>
            <ul className="section-list">
              {(data.evaluation_criteria || []).map((c, i) => <li key={i}>{c}</li>)}
            </ul>
          </div>

          {data.red_flags?.length > 0 && (
            <div className="result-card">
              <p className="result-label">Red Flags to Watch</p>
              <ul className="warning-list">
                {data.red_flags.map((f, i) => <li key={i}>{f}</li>)}
              </ul>
            </div>
          )}

          {data.onboarding_tips?.length > 0 && (
            <div className="result-card">
              <p className="result-label">Onboarding Tips</p>
              <ul className="section-list">
                {data.onboarding_tips.map((t, i) => <li key={i}>{t}</li>)}
              </ul>
            </div>
          )}

          <div className="report-toolbar no-print">
            <div className="report-toolbar-group">
              <span className="report-toolbar-label">Download</span>
              <button className="toolbar-btn" onClick={() => handleDownload("txt")}>TXT</button>
              <button className="toolbar-btn" onClick={() => handleDownload("md")}>MD</button>
              <button className="toolbar-btn" onClick={() => handleDownload("pdf")}>Print / PDF</button>
            </div>
            <div className="report-toolbar-divider" />
            <form className="report-toolbar-group" onSubmit={handleEmail}>
              <span className="report-toolbar-label">Email</span>
              <input
                type="email"
                className="toolbar-email-input"
                value={emailTo}
                onChange={(e) => { setEmailTo(e.target.value); setEmailSent(false); }}
                placeholder="recipient@email.com"
                required
                disabled={emailLoading}
              />
              <button type="submit" className="toolbar-btn toolbar-btn-primary" disabled={emailLoading}>
                {emailLoading ? "Sending…" : "Send"}
              </button>
            </form>
          </div>

          {emailSent && <p className="report-toolbar-success no-print">Report sent to {emailTo}</p>}
          {emailError && <div className="error-banner no-print" style={{ marginTop: "0.5rem" }}>{emailError}</div>}
        </>
      )}
    </div>
  );
}
