import { useState } from "react";
import { post } from "../../api/client";

function triggerDownload(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function slug(text) {
  return (text || "").toLowerCase().replace(/\s+/g, "_").replace(/[^a-z0-9_]/g, "") || "report";
}

function txtToHtml(txt, subject) {
  const lines = txt.split("\n");
  let body = "";
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const next = lines[i + 1] || "";
    const isSep = (s) => /^[=\-]{8,}$/.test(s);

    // Skip pure separator lines
    if (isSep(line)) { i++; continue; }

    // Section heading: line followed by a separator
    if (isSep(next) && line.trim()) {
      const isTitle = i === 0;
      if (!isTitle) {
        body += `<h2 style="color:#2563eb;font-size:0.85rem;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;margin:28px 0 8px;padding-bottom:4px;border-bottom:1px solid #e5e7eb">${line.trim()}</h2>`;
      }
      i += 2;
      continue;
    }

    // Empty line
    if (!line.trim()) { i++; continue; }

    // Numbered item — group consecutive numbered lines into an <ol>
    if (/^\d+\.\s/.test(line)) {
      body += '<ol style="margin:0 0 12px;padding-left:1.4rem">';
      while (i < lines.length && /^\d+\.\s/.test(lines[i])) {
        const text = lines[i].replace(/^\d+\.\s/, "");
        body += `<li style="font-size:0.91rem;line-height:1.6;margin-bottom:5px;color:#1f2937">${text}</li>`;
        i++;
      }
      body += "</ol>";
      continue;
    }

    // Key: Value lines (e.g. "Overall Risk: HIGH")
    if (/^[^:]+:\s.+/.test(line) && line.length < 80) {
      const colon = line.indexOf(":");
      const key = line.slice(0, colon).trim();
      const val = line.slice(colon + 1).trim();
      body += `<p style="margin:6px 0;font-size:0.91rem"><strong>${key}:</strong> ${val}</p>`;
      i++;
      continue;
    }

    // Regular paragraph
    body += `<p style="font-size:0.92rem;line-height:1.65;color:#1f2937;margin:0 0 10px">${line.trim()}</p>`;
    i++;
  }

  return `<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f3f4f6">
<div style="font-family:Inter,system-ui,sans-serif;max-width:640px;margin:32px auto;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,0.08)">
  <div style="background:#1e293b;padding:20px 28px 18px">
    <p style="margin:0 0 4px;font-size:0.8rem;font-weight:700;color:#94a3b8;text-transform:uppercase;letter-spacing:0.08em">Torres Tech Remote</p>
    <p style="margin:0;font-size:1.15rem;font-weight:800;color:#fff">${subject}</p>
  </div>
  <div style="padding:24px 28px 28px">
    ${body}
  </div>
  <div style="background:#f8fafc;padding:14px 28px;border-top:1px solid #e5e7eb">
    <p style="margin:0;font-size:0.75rem;color:#94a3b8">Generated by <strong>Workblox Business</strong> — Torres Tech Remote</p>
  </div>
</div>
</body>
</html>`;
}

export default function ReportToolbar({ filename, subject, txtContent, mdContent, htmlContent }) {
  const [emailTo, setEmailTo] = useState(localStorage.getItem("wbb_email") || "");
  const [emailSent, setEmailSent] = useState(false);
  const [emailLoading, setEmailLoading] = useState(false);
  const [emailError, setEmailError] = useState(null);

  async function handleEmail(e) {
    e.preventDefault();
    setEmailLoading(true);
    setEmailError(null);
    setEmailSent(false);
    try {
      await post("/api/biz/send-report", {
        email: emailTo,
        subject,
        content_txt: txtContent,
        content_html: htmlContent || txtToHtml(txtContent, subject),
      });
      setEmailSent(true);
    } catch (err) {
      setEmailError(err.message);
    } finally {
      setEmailLoading(false);
    }
  }

  return (
    <>
      <div className="report-toolbar no-print">
        <div className="report-toolbar-group">
          <span className="report-toolbar-label">Download</span>
          <button className="toolbar-btn" onClick={() => triggerDownload(txtContent, `${filename}.txt`, "text/plain")}>TXT</button>
          <button className="toolbar-btn" onClick={() => triggerDownload(mdContent || txtContent, `${filename}.md`, "text/markdown")}>MD</button>
          <button className="toolbar-btn" onClick={() => window.print()}>Print / PDF</button>
        </div>
        <div className="report-toolbar-divider" />
        <form className="report-toolbar-group" onSubmit={handleEmail}>
          <span className="report-toolbar-label">Email</span>
          <input
            type="email"
            className="toolbar-email-input"
            value={emailTo}
            onChange={(e) => { setEmailTo(e.target.value); setEmailSent(false); }}
            placeholder="recipient@email.com"
            required
            disabled={emailLoading}
          />
          <button type="submit" className="toolbar-btn toolbar-btn-primary" disabled={emailLoading}>
            {emailLoading ? "Sending…" : "Send"}
          </button>
        </form>
      </div>
      {emailSent && <p className="report-toolbar-success no-print">Report sent to {emailTo}</p>}
      {emailError && <div className="error-banner no-print" style={{ marginTop: "0.5rem" }}>{emailError}</div>}
    </>
  );
}
