import os
import re
import smtplib
import socket
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path


class _SMTP4(smtplib.SMTP):
    """SMTP subclass that forces an IPv4 connection."""
    def _get_socket(self, host, port, timeout):
        addrs = socket.getaddrinfo(host, port, socket.AF_INET, socket.SOCK_STREAM)
        if not addrs:
            raise OSError(f"No IPv4 address found for {host}")
        af, socktype, proto, _, sa = addrs[0]
        sock = socket.socket(af, socktype, proto)
        if timeout is not socket._GLOBAL_DEFAULT_TIMEOUT:
            sock.settimeout(timeout)
        sock.connect(sa)
        return sock

from flask import Blueprint, jsonify, request

from app.services import claude_client
from app.services.file_handler import extract_text

bp = Blueprint("doc_analyzer", __name__)

EMAIL_RE = re.compile(r"^[^@]+@[^@]+\.[^@]+$")

SYSTEM_PROMPT = """\
You are a helpful document analyst. Analyze the provided document and return a JSON object with exactly these four keys:
- "summary": A 2-3 sentence overview of the document.
- "key_data_points": A list of important names, dates, amounts, or figures as bullet points.
- "action_items": A list of tasks, deadlines, or next steps. If none, return ["None identified."].
- "red_flags": A list of concerns, risks, or missing information. If none, return ["None identified."].

Return only valid JSON. No markdown fences, no extra text.
"""


def _build_txt_report(filename: str, result: dict) -> str:
    lines = [
        f"ANALYSIS REPORT: {filename}",
        "Generated by Workblox — Torres Tech Remote",
        "",
    ]
    sections = [
        ("SUMMARY", result.get("summary", "")),
        ("KEY DATA POINTS", result.get("key_data_points", [])),
        ("ACTION ITEMS", result.get("action_items", [])),
        ("RED FLAGS", result.get("red_flags", [])),
    ]
    for title, content in sections:
        lines.append(title)
        lines.append("-" * len(title))
        if isinstance(content, list):
            for item in content:
                lines.append(f"  - {item}")
        else:
            lines.append(content)
        lines.append("")
    return "\n".join(lines)


@bp.post("/api/doc")
def doc_analyzer():
    if "file" not in request.files:
        return jsonify({"error": "file is required"}), 400
    file = request.files["file"]
    if not file.filename:
        return jsonify({"error": "no file selected"}), 400

    try:
        text = extract_text(file)
    except ValueError as e:
        return jsonify({"error": str(e)}), 415
    except Exception as e:
        return jsonify({"error": f"Could not read file: {e}"}), 422

    if not text.strip():
        return jsonify({"error": "Could not extract any text from the file"}), 422

    try:
        result = claude_client.call(
            system_prompt=SYSTEM_PROMPT,
            user_message=f"Document: {file.filename}\n\nContent:\n{text}",
            model="claude-sonnet-4-6",
            max_tokens=2048,
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 500

    return jsonify(result)


@bp.post("/api/doc/email")
def doc_email():
    body = request.get_json(silent=True) or {}
    email_addr = (body.get("email") or "").strip()
    filename = (body.get("filename") or "document").strip()
    result = body.get("result")

    if not email_addr or not EMAIL_RE.match(email_addr):
        return jsonify({"error": "Valid email address is required"}), 400
    if not result:
        return jsonify({"error": "result is required"}), 400

    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    if not smtp_user or not smtp_pass:
        return jsonify({"error": "Email is not configured on this server"}), 503

    txt_report = _build_txt_report(filename, result)
    stem = Path(filename).stem

    msg = MIMEMultipart()
    msg["From"] = smtp_user
    msg["To"] = email_addr
    msg["Subject"] = f"Doc Analyzer Report: {filename}"
    msg.attach(MIMEText(
        "Your document analysis report is attached.\n\n"
        "Generated by Workblox — Torres Tech Remote",
        "plain",
    ))

    attachment = MIMEBase("application", "octet-stream")
    attachment.set_payload(txt_report.encode("utf-8"))
    encoders.encode_base64(attachment)
    attachment.add_header(
        "Content-Disposition", f'attachment; filename="{stem}_report.txt"'
    )
    msg.attach(attachment)

    try:
        smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
        smtp_port = int(os.getenv("SMTP_PORT", "465"))
        with smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=15) as server:
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, email_addr, msg.as_string())
    except Exception as e:
        return jsonify({"error": f"Failed to send email: {e}"}), 500

    return jsonify({"success": True})
