import base64
import json
import os
import re
import urllib.request
from pathlib import Path

from flask import Blueprint, jsonify, request

from app.services import claude_client
from app.services.file_handler import extract_text

bp = Blueprint("doc_analyzer", __name__)

EMAIL_RE = re.compile(r"^[^@]+@[^@]+\.[^@]+$")

SYSTEM_PROMPT = """\
You are a helpful document analyst. Analyze the provided document and return a JSON object with exactly these four keys:
- "summary": A 2-3 sentence overview of the document.
- "key_data_points": A list of important names, dates, amounts, or figures as bullet points.
- "action_items": A list of tasks, deadlines, or next steps. If none, return ["None identified."].
- "red_flags": A list of concerns, risks, or missing information. If none, return ["None identified."].

Return only valid JSON. No markdown fences, no extra text.
"""


def _build_txt_report(filename: str, result: dict) -> str:
    lines = [
        f"ANALYSIS REPORT: {filename}",
        "Generated by Workblox — Torres Tech Remote",
        "",
    ]
    sections = [
        ("SUMMARY", result.get("summary", "")),
        ("KEY DATA POINTS", result.get("key_data_points", [])),
        ("ACTION ITEMS", result.get("action_items", [])),
        ("RED FLAGS", result.get("red_flags", [])),
    ]
    for title, content in sections:
        lines.append(title)
        lines.append("-" * len(title))
        if isinstance(content, list):
            for item in content:
                lines.append(f"  - {item}")
        else:
            lines.append(content)
        lines.append("")
    return "\n".join(lines)


def _send_via_resend(to_addr: str, filename: str, txt_report: str) -> None:
    api_key = os.getenv("RESEND_API_KEY")
    if not api_key:
        raise ValueError("Email is not configured on this server")

    stem = Path(filename).stem
    payload = {
        "from": "Workblox <onboarding@resend.dev>",
        "to": [to_addr],
        "subject": f"Doc Analyzer Report: {filename}",
        "text": "Your document analysis report is attached.\n\nGenerated by Workblox — Torres Tech Remote",
        "attachments": [{
            "filename": f"{stem}_report.txt",
            "content": base64.b64encode(txt_report.encode("utf-8")).decode(),
        }],
    }

    req = urllib.request.Request(
        "https://api.resend.com/emails",
        data=json.dumps(payload).encode(),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            resp.read()
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Resend API error {e.code}: {body}") from None


@bp.post("/api/doc")
def doc_analyzer():
    if "file" not in request.files:
        return jsonify({"error": "file is required"}), 400
    file = request.files["file"]
    if not file.filename:
        return jsonify({"error": "no file selected"}), 400

    try:
        text = extract_text(file)
    except ValueError as e:
        return jsonify({"error": str(e)}), 415
    except Exception as e:
        return jsonify({"error": f"Could not read file: {e}"}), 422

    if not text.strip():
        return jsonify({"error": "Could not extract any text from the file"}), 422

    try:
        result = claude_client.call(
            system_prompt=SYSTEM_PROMPT,
            user_message=f"Document: {file.filename}\n\nContent:\n{text}",
            model="claude-sonnet-4-6",
            max_tokens=2048,
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 500

    return jsonify(result)


@bp.post("/api/doc/email")
def doc_email():
    body = request.get_json(silent=True) or {}
    email_addr = (body.get("email") or "").strip()
    filename = (body.get("filename") or "document").strip()
    result = body.get("result")

    if not email_addr or not EMAIL_RE.match(email_addr):
        return jsonify({"error": "Valid email address is required"}), 400
    if not result:
        return jsonify({"error": "result is required"}), 400

    txt_report = _build_txt_report(filename, result)

    try:
        _send_via_resend(email_addr, filename, txt_report)
    except ValueError as e:
        return jsonify({"error": str(e)}), 503
    except Exception as e:
        return jsonify({"error": str(e)}), 500

    return jsonify({"success": True})
