import base64
import io
import json
import os
import re
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

from flask import Blueprint, jsonify, request, send_file

from app import limiter
from app.services import claude_client
from app.services.file_handler import extract_text

bp = Blueprint("doc_analyzer", __name__)

EMAIL_RE = re.compile(r"^[^@]+@[^@]+\.[^@]+$")
FROM_EMAIL = "pedro_torres@torrestechremote.com"
FROM_NAME = "Torres Tech Remote"

SYSTEM_PROMPT = """\
You are a helpful document analyst. Analyze the provided document and return a JSON object with exactly these four keys:
- "summary": A 2-3 sentence overview of the document.
- "key_data_points": A list of important names, dates, amounts, or figures as bullet points.
- "action_items": A list of tasks, deadlines, or next steps. If none, return ["None identified."].
- "red_flags": A list of concerns, risks, or missing information. If none, return ["None identified."].

Return only valid JSON. No markdown fences, no extra text.
"""


def _build_txt_report(filename: str, result: dict) -> str:
    lines = [
        f"ANALYSIS REPORT: {filename}",
        "Generated by Workblox — Torres Tech Remote",
        "",
    ]
    sections = [
        ("SUMMARY", result.get("summary", "")),
        ("KEY DATA POINTS", result.get("key_data_points", [])),
        ("ACTION ITEMS", result.get("action_items", [])),
        ("RED FLAGS", result.get("red_flags", [])),
    ]
    for title, content in sections:
        lines.append(title)
        lines.append("-" * len(title))
        if isinstance(content, list):
            for item in content:
                lines.append(f"  - {item}")
        else:
            lines.append(content)
        lines.append("")
    return "\n".join(lines)


@bp.post("/api/doc")
@limiter.limit("10 per hour")
def doc_analyzer():
    if "file" not in request.files:
        return jsonify({"error": "file is required"}), 400
    file = request.files["file"]
    if not file.filename:
        return jsonify({"error": "no file selected"}), 400

    try:
        text = extract_text(file)
    except ValueError as e:
        return jsonify({"error": str(e)}), 415
    except Exception as e:
        return jsonify({"error": f"Could not read file: {e}"}), 422

    if not text.strip():
        return jsonify({"error": "Could not extract any text from the file"}), 422

    try:
        result = claude_client.call(
            system_prompt=SYSTEM_PROMPT,
            user_message=f"Document: {file.filename}\n\nContent:\n{text}",
            model="claude-sonnet-4-6",
            max_tokens=2048,
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 500

    return jsonify(result)


@bp.post("/api/doc/download/pdf")
@limiter.limit("10 per hour")
def doc_download_pdf():
    from fpdf import FPDF

    FONT_DIR  = os.path.join(os.path.dirname(__file__), "..", "..", "fonts")
    FONT_REG  = os.path.join(FONT_DIR, "DejaVuSans.ttf")
    FONT_BOLD = os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")

    body     = request.get_json(silent=True) or {}
    filename = (body.get("filename") or "document").strip()
    result   = body.get("result")
    if not result:
        return jsonify({"error": "result is required"}), 400

    C_INK   = (15,  23,  42)
    C_BLUE  = (37,  99, 235)
    C_SOFT  = (100,116, 139)
    C_RED   = (220, 38,  38)
    C_RULE  = (226,232, 240)
    W = 180

    class _PDF(FPDF):
        def __init__(self):
            super().__init__()
            self.add_font("DJ", "",  FONT_REG)
            self.add_font("DJ", "B", FONT_BOLD)

        def sec(self, title, color):
            self.ln(4)
            self.set_font("DJ", "B", 8)
            self.set_text_color(*color)
            self.cell(W, 5, title.upper())
            self.ln(5)
            self.set_draw_color(*color)
            self.set_line_width(0.3)
            self.line(15, self.get_y(), 195, self.get_y())
            self.ln(3)
            self.set_text_color(*C_INK)
            self.set_draw_color(0, 0, 0)

    pdf = _PDF()
    pdf.set_auto_page_break(True, 15)
    pdf.add_page()
    pdf.set_margins(15, 15, 15)

    pdf.set_fill_color(*C_INK)
    pdf.rect(0, 0, 210, 26, "F")
    pdf.set_xy(15, 7)
    pdf.set_font("DJ", "B", 13)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(W, 7, "Document Analysis Report")
    pdf.ln(8)
    pdf.set_x(15)
    pdf.set_font("DJ", "", 8.5)
    pdf.set_text_color(180, 190, 210)
    now = datetime.now().strftime("%B %d, %Y  %H:%M")
    pdf.cell(W, 5, f"{filename}   |   {now}   |   Workblox — Torres Tech Remote")
    pdf.ln(16)

    sections = [
        ("Summary",         result.get("summary", ""),           C_BLUE, False),
        ("Key Data Points", result.get("key_data_points", []),   C_BLUE, True),
        ("Action Items",    result.get("action_items", []),       C_BLUE, True),
        ("Red Flags",       result.get("red_flags", []),          C_RED,  True),
    ]
    for title, content, color, is_list in sections:
        pdf.sec(title, color)
        pdf.set_font("DJ", "", 9.5)
        pdf.set_text_color(*C_INK)
        if is_list and isinstance(content, list):
            for item in content:
                pdf.set_x(15)
                pdf.cell(5, 6, "•")
                pdf.set_x(20)
                pdf.multi_cell(W - 5, 6, item)
        else:
            pdf.set_x(15)
            pdf.multi_cell(W, 6, str(content))
        pdf.ln(1)

    pdf.set_auto_page_break(False)
    pdf.set_y(pdf.h - 14)
    pdf.set_font("DJ", "", 7.5)
    pdf.set_text_color(*C_SOFT)
    pdf.cell(W, 5, f"Generated by Workblox — Torres Tech Remote  |  {now}", align="C")

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    stem = Path(filename).stem
    return send_file(buf, as_attachment=True,
        download_name=f"{stem}_report.pdf",
        mimetype="application/pdf")


@bp.post("/api/doc/email")
@limiter.limit("10 per hour")
def doc_email():
    body = request.get_json(silent=True) or {}
    email_addr = (body.get("email") or "").strip()
    filename = (body.get("filename") or "document").strip()
    result = body.get("result")

    if not email_addr or not EMAIL_RE.match(email_addr):
        return jsonify({"error": "Valid email address is required"}), 400
    if not result:
        return jsonify({"error": "result is required"}), 400

    api_key = os.getenv("SENDGRID_API_KEY")
    if not api_key:
        return jsonify({"error": "Email is not configured on this server"}), 503

    txt_report = _build_txt_report(filename, result)
    stem = Path(filename).stem

    payload = {
        "personalizations": [{"to": [{"email": email_addr}]}],
        "from": {"email": FROM_EMAIL, "name": FROM_NAME},
        "subject": f"Doc Analyzer Report: {filename}",
        "content": [{"type": "text/plain", "value": (
            "Your document analysis report is attached.\n\n"
            "Generated by Workblox — Torres Tech Remote"
        )}],
        "attachments": [{
            "content": base64.b64encode(txt_report.encode("utf-8")).decode(),
            "type": "text/plain",
            "filename": f"{stem}_report.txt",
        }],
    }

    req = urllib.request.Request(
        "https://api.sendgrid.com/v3/mail/send",
        data=json.dumps(payload).encode(),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            resp.read()
    except urllib.error.HTTPError as e:
        body_err = e.read().decode("utf-8", errors="replace")
        return jsonify({"error": f"SendGrid error {e.code}: {body_err}"}), 500

    return jsonify({"success": True})
